name: Build/release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Build Application
        run: npm install && npm run package

      - name: Zip the build
        run: zip -r AmbientBuddy out
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: AmbientBuddy.zip